# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://oegedijk.github.io/dash_oop_components/"

git_url = "https://github.com/oegedijk/dash_oop_components/tree/master/"

def custom_doc_links(name): return None
