# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"DashComponentBase": "00_core.ipynb",
         "DashFigureFactory": "00_core.ipynb",
         "DashComponent": "00_core.ipynb",
         "DashComponentTabs": "00_core.ipynb",
         "DashConnector": "00_core.ipynb",
         "concat_docstring": "00_core.ipynb",
         "parse_url_to_params": "00_core.ipynb",
         "parse_url_to_qs_and_vals": "00_core.ipynb",
         "encode_querystring_params_to_url": "00_core.ipynb",
         "update_url_with_new_params": "00_core.ipynb",
         "DashApp": "00_core.ipynb",
         "dashapp": "01_cli.ipynb"}

modules = ["core.py",
           "cli.py"]

doc_url = "https://oegedijk.github.io/dash_oop_components/"

git_url = "https://github.com/oegedijk/dash_oop_components/tree/master/"

def custom_doc_links(name): return None
